name: instagram_clone
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  domain:
    path: domain
  sqflite: ^2.0.0+3
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  json_serializable: ^4.1.0
  rxdart: ^0.26.0
  intl: ^0.17.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: fonts/proxima_nova_regular.ttf
        - asset: fonts/proxima_nova_light.ttf
          weight: 300
        - asset: fonts/proxima_nova_bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  main_locale: eng
